export const Projects = [
  {
    num: "01",
    category: "MERN Stack",
    title: "project 1",
    description:
      "Developed a MERN stack website that facilitates doctor listings, service browsing, and appointment scheduling, while enabling doctors to coordinate and respond to patient requests effectively.",
    stack: [
      { name: "React.js" },
      { name: "Tailwind.css" },
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "MongoDB" },
      { name: "Firebase" },
    ],
    // image: "/assets/projects/poor-doct.png",
    image: "/assets/projects/poor-doct-Copy.png",
    live: "https://poor-doct.web.app/",
    github: "https://github.com/riponmondalbd/poor-doct",
  },
  {
    num: "02",
    category: "MERN Stack",
    title: "project 2",
    description:
      "Developed a full MERN stack website where users can view restaurant menus and place orders, while admins can manage, update, delete, and deliver orders, as well as assign admin roles.",
    stack: [
      { name: "React.js" },
      { name: "Tailwind.css" },
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "MongoDB" },
      { name: "Firebase" },
    ],
    image: "/assets/projects/bistro-boss.png",
    live: "https://bistro-boss-restaurant-b46d3.web.app/",
    github: "https://github.com/riponmondalbd/bistro-boss-restaurant-v2",
  },
  {
    num: "03",
    category: "Fullstack",
    title: "project 3",
    description:
      "Developed a fullstack website that facilitates show my project. It is a portfolio project.",
    stack: [{ name: "Next.js" }, { name: "Tailwind.css" }],
    image: "/assets/projects/portfolio.png",
    live: "https://portfolio-ripon-mondal.vercel.app/",
    github: "https://github.com/riponmondalbd/portfolio",
  },
  {
    num: "04",
    category: "Fullstack",
    title: "project 4",
    description:
      "Built a full MERN stack job portal where users can view and apply for jobs, with permission-based access upon login. Each user has a custom dashboard to manage and track activity.",
    stack: [
      { name: "React.js" },
      { name: "Tailwind.css" },
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "MongoDB" },
      { name: "Firebase" },
    ],
    image: "/assets/projects/job-portal.png",
    live: "https://job-portal-fb670.web.app",
    github: "https://github.com/riponmondalbd/job-portal",
  },
  {
    num: "05",
    category: "Frontend",
    title: "project 5",
    description:
      "Developed a fullstack website that facilitates manage book and also review system of books.",
    stack: [{ name: "React.js" }, { name: "Tailwind.css" }],
    image: "/assets/projects/book-review.png",
    live: "https://book-reviewp.netlify.app",
    github: "https://github.com/riponmondalbd/book-review",
  },
  {
    num: "06",
    category: "Frontend",
    title: "project 6",
    description:
      "Developed a fullstack website that make to based on online e-news paper.",
    stack: [{ name: "React.js" }, { name: "Tailwind.css" }],
    image: "/assets/projects/dragon-newspaper.png",
    live: "https://latest-dragon-news.surge.sh",
    github: "https://github.com/riponmondalbd/book-review",
  },
  {
    num: "07",
    category: "Fullstack",
    title: "project 7",
    description:
      "Developed a fullstack website that facilitates show my project. It is a portfolio project.",
    stack: [{ name: "Next.js" }, { name: "Tailwind.css" }],
    image: "/assets/projects/portfilio-new.png",
    live: "https://latest-dragon-news.surge.sh",
    github: "https://github.com/riponmondalbd/book-review",
  },
  {
    num: "08",
    category: "Fullstack",
    title: "project 8",
    description:
      "Developed a fullstack website that facilitates show my project. It is a portfolio project.",
    stack: [
      { name: "react.js" },
      { name: "Tailwind.css" },
      { name: "firebase" },
    ],
    image: "/assets/projects/real-state.png",
    live: "https://real-estate-50c3a.web.app/",
    github: "https://github.com/riponmondalbd/real-estate",
  },
];
